---
- name: Setup frontend load-balancer tier
  hosts: frontends
  gather_facts: false
  tags:
    - frontends

  roles:
    - common
    - frontend-tier

# Setup application servers tier

- name: Setup app tier
  hosts: apps
  tags:
    - apps

  roles:
    - common
    - app-tier

# Setup database tier

- name: Setup database tier
  hosts: appdbs
  tags:
    - databases

  roles:
    - common
    - geerlingguy.postgresql
...
